### ISSUE TITLE
Index design v2 task list

### ISSUE THREAD

**Issue by adrian-wang** [Intel-bigdata/OAP#319]
- [ ] add more detailed statistics in data header (pending design doc)
- [ ] Optimize B+Tree for partial loading (pending design doc)
- [ ] implement partial loading mechanism (pending design doc)
- [ ] add encoding support in index file (pending design doc)
- [ ] index fiber group and index fiber caching and evicting (pending now)
- [ ] optimize bitmap index (pending design doc)
- [ ] implement permuterm index for like operation. (on going)
- [ ] operator to upgrade(rebuild) meta and index file
- [ ] tool to check file consistency

**Comment by adrian-wang** [comment]
I'm starting from the top, any one want to pick up something, please tell me.

**Comment by adrian-wang** [comment]
close this since it goes too far from this plan
