### ISSUE TITLE
Parquet Use OapFileFormat Support Vectorized Read

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#536]
Last week I research the optimization of parquet use OapFileFormat but not indexed read, perhaps we can use the “Vectorized Read + Batch Return” implementation as ParquetFileFormat，and research content in the following google-doc: 

https://docs.google.com/document/d/19jaw920tFS1YXg1feYKoQ4e_n2-Rhr3ERDT2vwyP5xY/edit?usp=sharing

- [x] 1.Copy ColumnarBatch.java & ColumnarBatchSuite.scala from spark-2.1 #568 

- [x] 2.Exact some utils & refact ascaded parquet code #575 

- [x] 3.Pushed Filter from OapFileFormat #576

- [x] 4.Add VectorizedOapRecordReader & test case #581

- [x] 5.Add IndexedVectorizedOapRecordReader & test case #592

- [x] 6.Oap use VectorizedReader read Parquet  #603

- [ ]  7. Add a benchmark to compare Readers include  #619 
7.1 Parquet MR vs Parquet Vectorized vs Oap Parquet Vectorized  
7.2 Indexed Parquet MR vs Indexed Parquet Vectorized

Task 1&2&3 can Parallelable

**Comment by linhong-intel** [comment]
Thanks @LuciferYang 
just want to be clarified:
Can we only enable "vectorized read" for fallback reading? since in my understanding, this won't involve any changes in OAP. But I don't know the performance of "vectorized read only".

regarding the batch return:
Can you give some reasons about why batch return can accelerate reading in you docs?

**Comment by Moonlit-Sailor** [comment]
Really cool features!! Thanks @LuciferYang 
I've reviewed partly and left some ideas.
I don't know if my opinions make sense, glad to receive your reply if I don't understand correctly.
Keep in touch on this feature  : )
