### ISSUE TITLE
Optimize nextBatch() method of IndexedVectorizedOapRecordReader

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#825]
Now `nextBatch()` method of `IndexedVectorizedOapRecordReader` call `super.nextBatch()` method to load data to `columnarBatch` use `columnReaders`, then call `filterRowsWithIndex()` method to mark valid rows in `columnarBatch` or recursive call `nextBatch()` method if no valid data in current batch, this process is correct but not efficient. 

If we have a less columns but more records data file and we need data in first batch and last batch, use this strategy we have to load ervery columnarBatch even if we only need the first and the last.
So I want try to add a new `skipBatch` method to solve this problem, then we can only modify the state instead of load data to `columnarBatch` when no valid data in nextBatch.

- [x] import `VectorizedRleValuesReader`, `VectorizedPlainValuesReader` ,`VectorizedRleValuesReader` from spark-2.1 code #836 

- [x] Add skip capacity for`VectorizedRleValuesReader` &`VectorizedPlainValuesReader` #845 

- [x] Add skip capacity  for `VectorizedColumnReader` #856 

- [ ] Add skip capacity  for `IndexedVectorizedOapRecordReader` to reduce `ColumnVector` assembly times #870

**Comment by gczsjdy** [comment]
Good catch ! : )
